version: '3.7'

services:

  web-db:
    image: postgres:12-alpine
    expose:
      - 5432
    env_file:
      - app/.envs/.postgres

  web:
    build: ./app
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - app/.envs/.postgres
    depends_on:
      - web-db